version: "3"

services:
  web: &web
    tty: true
    stdin_open: true
    image: hodai1508/emagazine:dev
    build:
      context: .
      dockerfile: Dockerfile
    command: sh docker/start.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - web.env
    depends_on:
      - db

  db:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: emagazine_dev
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  sidekiq: &sidekiq
    image: hodai1508/emagazine:dev
    command: docker/start_sidekiq.sh
    volumes:
      - .:/app
    env_file:
      - web.env
    depends_on:
      - redis
volumes:
  bundle:
