default: &default
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] || ENV['MYSQL_ROOT_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'emagazine_dev' } %>

test:
  <<: *default
  database: emagazine_test

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PRO") { 'emagazine_pro' } %>
